name: Basic CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm run test
      
    - name: Build application
      run: npm run build

  # Job 2: Build and push Docker image (only on main push)
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Yandex Cloud Container Registry
      uses: docker/login-action@v3
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          cr.yandex/crp18f0881clcu82u2d8/app:latest
          cr.yandex/crp18f0881clcu82u2d8/app:${{ github.run_number }}

  # Job 3: Deploy to Yandex Cloud VM (only on main push)
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Yandex Cloud VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 84.201.149.172
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Login to Yandex Container Registry
          echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' | docker login --username json_key --password-stdin cr.yandex
          
          # Stop existing container (if running)
          docker stop shri-app || true
          docker rm shri-app || true
          
          # Pull latest image
          docker pull cr.yandex/crp18f0881clcu82u2d8/app:latest
          
          # Run new container
          docker run -d \
            --name shri-app \
            --restart unless-stopped \
            -p 3000:3000 \
            cr.yandex/crp18f0881clcu82u2d8/app:latest 